### ISSUE TITLE
Utils muss auch ins maven repo

### ISSUE THREAD

**Issue by cirk2** [cyface-de/android-backend#100]
https://github.com/cyface-de/android-backend/blob/a612ab3ee296b9c4171966d7c8bfe71ffbb5ada6/build.gradle#L80

Hier fehlt der Eintrag "utils" im Array

**Comment by hb0** [comment]
Danke für's Feedback!
Ich habe das in die eben releaste Version 3.3.0 mit aufgenommen.
Ich schließe das Issue das das nun erledigt sein sollte.
